version: 2
updates:
- package-ecosystem: cargo
  directory: "/2019"
  schedule:
    interval: monthly
  # Disable pull requests on this directory
  open-pull-requests-limit: 0

- package-ecosystem: cargo
  directory: "/2020"
  schedule:
    interval: monthly
  # Disable pull requests on this directory
  open-pull-requests-limit: 0

- package-ecosystem: npm
  directory: "/2021"
  schedule:
    interval: monthly
  # Disable pull requests on this directory
  open-pull-requests-limit: 0

- package-ecosystem: cargo
  directory: "/2022"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  assignees:
  - "JayRovacsek"
